/**
 * Comprehensive list of medicines for the prescription pad
 * Organized alphabetically for easy search
 */
export const MEDICINES_LIST: string[] = [
    // A
    "Aciclovir (Zovirax)",
    "Acrivastine",
    "Adalimumab",
    "Alendronic acid",
    "Allopurinol",
    "Alogliptin",
    "Amitriptyline",
    "Amlodipine",
    "Amoxicillin",
    "Anastrozole",
    "Apixaban",
    "Aripiprazole",
    "Aspirin (Low-dose)",
    "Aspirin (Pain relief)",
    "Atenolol",
    "Atorvastatin",
    "Azathioprine",
    "Azithromycin",
    // B
    "Baclofen",
    "Beclometasone inhaler",
    "Beclometasone nasal spray",
    "Beclometasone skin cream",
    "Bendroflumethiazide",
    "Benzoyl peroxide",
    "Benzydamine",
    "Betahistine",
    "Betamethasone (eyes/ears/nose)",
    "Betamethasone (skin)",
    "Bimatoprost (Lumigan)",
    "Bisacodyl",
    "Bismuth subsalicylate (Pepto-Bismol)",
    "Bisoprolol",
    "Brinzolamide",
    "Budesonide inhaler",
    "Budesonide nasal spray",
    "Budesonide rectal foam/enemas",
    "Bumetanide",
    "Buprenorphine",
    "Buscopan (Hyoscine butylbromide)",
    // C
    "Calcipotriol",
    "Candesartan",
    "Carbamazepine",
    "Carbimazole",
    "Carbocisteine",
    "Carmellose sodium eye drops",
    "Carvedilol",
    "Cefalexin",
    "Cetirizine",
    "Chloramphenicol",
    "Chlorhexidine",
    "Chlorphenamine (Piriton)",
    "Cinnarizine",
    "Ciprofloxacin",
    "Citalopram",
    "Clarithromycin",
    "Clobetasol",
    "Clobetasone",
    "Clonazepam",
    "Clonidine",
    "Clopidogrel",
    "Clotrimazole cream/spray",
    "Clotrimazole (Canesten)",
    "Co-amoxiclav",
    "Co-beneldopa",
    "Co-careldopa",
    "Co-codamol",
    "Co-dydramol",
    "Codeine",
    "Colchicine",
    "Colecalciferol",
    "Cyanocobalamin",
    "Cyclizine",
    // D
    "Dapagliflozin",
    "Dexamethasone eye drops",
    "Dexamethasone tablets",
    "Diazepam",
    "Diclofenac",
    "Digoxin",
    "Dihydrocodeine",
    "Diltiazem",
    "Diphenhydramine",
    "Dipyridamole",
    "Docusate",
    "Domperidone",
    "Donepezil",
    "Doxazosin",
    "Doxycycline",
    "Duloxetine",
    // E
    "Edoxaban",
    "Empagliflozin",
    "Enalapril",
    "Eplerenone",
    "Erythromycin",
    "Escitalopram",
    "Esomeprazole",
    "Ezetimibe",
    // F
    "Felodipine",
    "Fentanyl",
    "Ferrous fumarate",
    "Ferrous sulfate",
    "Fexofenadine",
    "Finasteride",
    "Flucloxacillin",
    "Fluconazole",
    "Fluoxetine (Prozac)",
    "Fluticasone inhaler",
    "Fluticasone nasal spray",
    "Fluticasone skin cream",
    "Folic acid",
    "Furosemide",
    "Fusidic acid (Fucidin)",
    "Fybogel (Ispaghula husk)",
    // G
    "Gabapentin",
    "Gaviscon",
    "Gliclazide",
    "Glyceryl trinitrate (GTN)",
    // H
    "Haloperidol",
    "Hydrocortisone buccal tablets",
    "Hydrocortisone cream (skin)",
    "Hydrocortisone injections",
    "Hydrocortisone rectal foam",
    "Hydrocortisone tablets",
    "Hydroxocobalamin",
    "Hydroxychloroquine",
    "Hyoscine hydrobromide (Kwells)",
    // I
    "Ibuprofen",
    "Ibuprofen + Codeine",
    "Indapamide",
    "Insulin",
    "Irbesartan",
    "Isosorbide mononitrate",
    "Isotretinoin (Roaccutane)",
    // K
    "Ketoconazole",
    // L
    "Lactulose",
    "Lamotrigine",
    "Lansoprazole",
    "Latanoprost",
    "Lercanidipine",
    "Letrozole",
    "Levetiracetam",
    "Levothyroxine",
    "Lidocaine skin cream",
    "Linagliptin",
    "Lisinopril",
    "Lithium",
    "Loperamide (Imodium)",
    "Loratadine (Clarityn)",
    "Lorazepam",
    "Losartan",
    "Lymecycline",
    // M
    "Macrogol",
    "Mebendazole",
    "Mebeverine",
    "Medroxyprogesterone tablets",
    "Melatonin",
    "Memantine",
    "Mesalazine",
    "Metformin",
    "Methadone",
    "Methotrexate",
    "Methylphenidate",
    "Metoclopramide",
    "Metoprolol",
    "Metronidazole",
    "Mirabegron",
    "Mirtazapine",
    "Mometasone (skin)",
    "Mometasone inhaler",
    "Mometasone nasal spray",
    "Montelukast",
    "Morphine",
    // N
    "Naproxen",
    "Nefopam",
    "Nicorandil",
    "Nifedipine",
    "Nitrofurantoin",
    "Nortriptyline",
    "Nystatin",
    // O
    "Olanzapine",
    "Omeprazole",
    "Oxybutynin",
    "Oxycodone",
    // P
    "Pantoprazole",
    "Paracetamol",
    "Paroxetine",
    "Peppermint oil",
    "Perindopril",
    "Phenoxymethylpenicillin",
    "Pravastatin",
    "Prednisolone",
    "Pregabalin",
    "Prochlorperazine",
    "Promethazine (Phenergan)",
    "Propranolol",
    "Pseudoephedrine (Sudafed)",
    // Q
    "Quetiapine",
    // R
    "Ramipril",
    "Ranitidine",
    "Risperidone",
    "Rivaroxaban",
    "Ropinirole",
    "Rosuvastatin",
    // S
    "Salbutamol inhaler",
    "Senna",
    "Sertraline",
    "Sildenafil",
    "Simeticone",
    "Simvastatin",
    "Sitagliptin",
    "Sodium valproate",
    "Solifenacin",
    "Sotalol",
    "Spironolactone",
    "Sulfasalazine",
    "Sumatriptan",
    // T
    "Tadalafil",
    "Tamsulosin",
    "Terbinafine",
    "Thiamine (Vitamin B1)",
    "Tibolone",
    "Ticagrelor",
    "Timolol eye drops",
    "Tiotropium inhaler",
    "Tolterodine",
    "Topiramate",
    "Tramadol",
    "Tranexamic acid",
    "Trastuzumab (Herceptin)",
    "Trazodone",
    "Trimethoprim",
    // U
    "Utrogestan (Micronised progesterone)",
    // V
    "Valproic acid",
    "Valsartan",
    "Varenicline",
    "Venlafaxine",
    "Verapamil",
    // W
    "Warfarin",
    // Z
    "Zolpidem",
    "Zopiclone",
];

/**
 * Lab tests available for ordering
 */
export const LAB_TESTS: string[] = [
    // Hematology
    "Complete Blood Count (CBC)",
    "Erythrocyte Sedimentation Rate (ESR)",
    "Prothrombin Time (PT/INR)",
    "Activated Partial Thromboplastin Time (APTT)",
    "D-Dimer",
    "Blood Group & Rh Factor",
    "Peripheral Blood Smear",
    "Reticulocyte Count",
    // Biochemistry
    "Blood Glucose (Fasting)",
    "Blood Glucose (Random)",
    "HbA1c (Glycated Hemoglobin)",
    "Oral Glucose Tolerance Test (OGTT)",
    "Kidney Function Tests (KFT/RFT)",
    "Liver Function Tests (LFT)",
    "Lipid Profile",
    "Serum Electrolytes (Na, K, Cl)",
    "Serum Calcium",
    "Serum Uric Acid",
    "Serum Iron & TIBC",
    "Serum Ferritin",
    "Vitamin D (25-OH)",
    "Vitamin B12",
    "Serum Magnesium",
    "Serum Phosphorus",
    "Serum Protein (Total & Albumin)",
    "C-Reactive Protein (CRP)",
    "Rheumatoid Factor (RF)",
    "Anti-Nuclear Antibody (ANA)",
    // Thyroid
    "Thyroid Function Tests (TFTs)",
    "TSH",
    "Free T3",
    "Free T4",
    // Cardiac
    "Troponin I/T",
    "CK-MB",
    "BNP / NT-proBNP",
    "Lipid Profile (Cardiac risk)",
    // Urinalysis
    "Urine Routine Examination",
    "Urine Culture & Sensitivity",
    "24-Hour Urine Protein",
    "Urine for Microalbumin",
    // Microbiology
    "Blood Culture & Sensitivity",
    "Sputum Culture & Sensitivity",
    "Wound Swab Culture",
    "Stool Routine & Culture",
    "Throat Swab Culture",
    // Serology / Immunology
    "Hepatitis B Surface Antigen (HBsAg)",
    "Hepatitis C Antibody (Anti-HCV)",
    "HIV 1 & 2 Antibody",
    "Dengue NS1 Antigen",
    "Dengue IgG / IgM",
    "Typhidot (Typhoid)",
    "Widal Test",
    "Malaria Parasite (MP)",
    "COVID-19 PCR",
    "COVID-19 Rapid Antigen",
    // Hormones
    "Testosterone",
    "Estradiol",
    "Progesterone",
    "Prolactin",
    "FSH & LH",
    "Cortisol (Morning)",
    "Insulin Level (Fasting)",
    "PSA (Prostate Specific Antigen)",
    "Beta-HCG (Pregnancy Test)",
    // Tumor Markers
    "CA-125",
    "CA 19-9",
    "CEA (Carcinoembryonic Antigen)",
    "AFP (Alpha Fetoprotein)",
    // Radiology Orders
    "X-Ray (Chest PA)",
    "X-Ray (Abdomen)",
    "X-Ray (Spine)",
    "X-Ray (Extremity)",
    "Ultrasound (Abdomen)",
    "Ultrasound (Pelvis)",
    "Ultrasound (KUB)",
    "CT Scan (Head)",
    "CT Scan (Chest)",
    "CT Scan (Abdomen)",
    "MRI (Brain)",
    "MRI (Spine)",
    "MRI (Knee/Joint)",
    "Echocardiography (2D Echo)",
    "ECG (Electrocardiogram)",
    "Doppler Ultrasound",
];
